---
title: "microclimJuniper: Temperature from high mountain Juniper-thickets (Sierra Nevada, southern Spain)"
author: "Antonio J. Pérez"
output:
  flexdashboard::flex_dashboard:
    theme: paper
---

```{r setup, include=FALSE}
library("flexdashboard")
library("here")
library("sf")
library("tidyverse")  # tidy data manipulation
library("leaflet")  # interative mapping
library("DT")  # interactive tables
library("crosstalk") # inter-widget interactivity
library("dygraphs")
temperatura <- readRDS(here::here("data/temp_microenebral.rds")) %>% 
  dplyr::select(timestamp, temperature, validation, serial_number) 
sensores <- readRDS(here::here("data/temp_microenebral_spatial.rds"))

# Join
# temp <- temperatura %>% left_join(sensores, by = "serial_number")


# tempo <- st_sf(temp)
s <- SharedData$new(sensores)
```

Data Viewer {data-icon="ion-stats-bars"}
=====================================  

Column {data-width=300}
-------------------------------------
### Select sensor

```{r}
filter_select(
  id = "site",
  label = "Select Location",
  sharedData = s, ## 
  group = ~loc 
)
bscols(
  filter_checkbox(
    id = "microhabitat",
    label = "Microhabitat",
    sharedData = s,
    group = ~microhabitat
    ),
  filter_checkbox(
    id = "status",
    label = "Status",
    sharedData = s,
    group = ~status
  )
)
```

Column {data-width=700}
-----------------------------------------------------------------------

### Chart B

```{r}
s %>% 
  leaflet::leaflet() %>%
  leaflet::addProviderTiles(providers$OpenStreetMap) %>% 
  leaflet::addAwesomeMarkers(
    popup = ~paste0("<strong>Serial Number:</strong> ", sensores$serial_number, "</br>",
                    "<strong>Location:</strong> ", 
                     ifelse(sensores$loc == "HZM", "Haza Mesa (Güejar-Sierra)", "Bérchules"), "</br>",
                    "<strong>Status:</strong> ", sensores$status, "</br>",
                    "<strong>Microhabitat:</strong> ", sensores$microhabitat, "</br>",
                    "<strong>Start Date:</strong> ", sensores$start_time,"</br>",
                    "<strong>End Date:</strong> ", sensores$end_time),
    icon = awesomeIcons(
      library = "ion",
      icon = "ion-android-radio-button-off",
      iconColor = "white",
      markerColor = ifelse(
        test = sensores$status == "Ok", 
        yes = "green",
        no = "red"
      )
    )
  ) 
```

### Chart C
```{r datatable}
s %>% 
  DT::datatable(
    filter = "top",  # allows filtering on each column
    extensions = c(
      "Buttons",  # add download buttons, etc
      "Scroller"  # for scrolling down the rows rather than pagination
    ),
    rownames = FALSE,  # remove rownames
    style = "bootstrap",
    class = "compact",
    width = "100%",
    options = list(
      dom = "Blrtip",  # specify content (search box, etc)
      deferRender = TRUE,
      scrollY = 300,
      scroller = TRUE,
      columnDefs = list(
        list(
          visible = TRUE,
          targets = c(7,4,5)
        )
      ), 
      buttons = list(
        I("colvis"),  # turn columns on and off
        "csv",  # download as .csv
        "excel"  # download as .xlsx
      )
    )
    
    # colnames = c(
    #   "URN" = "sch_urn",
    #   "Name" = "sch_name",
    #   "Type" = "sch_type",
    #   "Type group" = "sch_type_group",
    #   "Phase" = "sch_phase",
    #   "Ofsted rating" = "ofsted_rating",
    #   "Inspection date" = "ofsted_date",
    #   "Pupil count" = "pupil_count",
    #   "Pupil gender" = "pupil_gender",
    #   "FSM per cent" = "pupil_percent_fsm",
    #   "Town" = "geo_town",
    #   "Postcode" = "geo_postcode",
    #   "Local authority" = "geo_la",
    #   "Rural-urban class" = "geo_urban_rural",
    #   "RSC region" = "geo_rsc_region",
    #   "Coordinates" = "geometry"
    # )
  )

```

